artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: sumit17125/red-wine-quality-dataset
  local_data_file: artifacts/data_ingestion/red-wine-quality-dataset.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data
