artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: sumit17125/red-wine-quality-dataset
  local_data_file: artifacts/data_ingestion/red-wine-quality-dataset.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data

data_validation:
  root_dir: artifacts/data_validation
  schema_file_path: schema.yaml
  status_file: artifacts/data_validation/status.txt
  unzip_data_path: artifacts/data_ingestion/unzipped_data/winequality-red.csv

data_visualization:
  data_path: artifacts/data_ingestion/unzipped_data/winequality-red.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/unzipped_data/winequality-red.csv
  scaler_path: artifacts/data_transformation/scaler.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl

